name: longscale
description: A scale recorder of baby care.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in:

  # UI
  cached_network_image:
  equatable:
  shared_preferences:

  # Utils
  intl:
  path_provider:
  uuid:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
